modLoader="javafml"
loaderVersion="[43,44)"
license="AGPL-3.0"

[[mods]]
    modId="spacedustry"
    version="0.2.0"

    displayName="Spacedustry"
    authors="NewJumper"
    description='''A mod for space travel!'''

[[dependencies.spacedustry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.19.3)"
    side="BOTH"

[[dependencies.spacedustry]]
    modId="forge"
    mandatory=true
    versionRange="[43,44)"
    side="BOTH"
