modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
    modId="spacedustry"
    version="0.1.0"

    displayName="Spacedustry"
    authors="NewJumper"
#    logoFile="examplemod.png"
    description='''A mod for space travel!'''

[[dependencies.spacedustry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    side="BOTH"

[[dependencies.spacedustry]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    side="BOTH"
